# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_articles'),
        ('article', '0003_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='tag.tag'),
        ),
    ]
